### ISSUE TITLE
storing args as json in localmeta is kind of awkward

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#139] opened 2020-09-02 06:37 UTC
because args are represented as Any in the structs we send over the wire it means that we have to round trip them to Any and then back to json to send them. i realize that if we stored them as json in the fb and then represented them as Any in the localmeta we would still do the same number of round trips, but at least the place that we could fail to decode the thing in the fb is when we are reading the commit, which makes sense. as it stands now we have to allow for the possibility that the args return an error when we attempt to decode them to Any which happens after we have a commit and at various points where we need to send them via rpc or http. i know validate_local_meta checks them so it is currently impossible that they dont decode properly but it still feels weird writing a panic when there is no way to return an error. for example i want to implement From(localmeta) which must succeed so i'm faced with the choice of doing it the non idiomatic way (not using From), or writing a much hated, widely panned and pathetic panic.

**Comment by aboodman** [comment] 2020-09-02 07:17
I think we should pass the args as a string. Does that help?

**Comment by aboodman** [comment] 2020-09-10 19:48
Duplicate of #151

**Closed by aboodman** 2020-09-10 19:48 UTC
