### ISSUE TITLE
repc testing

### ISSUE THREAD

**Issue by phritz** [rocicorp/repc#77] opened 2020-08-08 20:50 UTC
Working on sync brings to light some questions about how we are and should be testing repc.

**Assumptions/background:**
- http requests are an important part of the sync protocol
- as far as I can tell, by design we cannot easily run a web server when compiling to wasm in the browser (no sockets, eg). OK, sure, I can imagine some sort of http-over-websocket gymnastics, but that doesn't sound _easy_: something that works well off the shelf and doesn't make your head explode. This means that testing sync which requires http requests is necessarily going to be limited in the wasm-in-browser case because we can't run a web server. Mocking is of course an option.
- wasm-in-the-browser is not the only platform we're going to want to run on, for _example_ iOS and Android are enormous markets
- given the way we have architected repc, the main differences across platforms seem likely to be 1) how http requests are made and 2) the kv store implementation we use, and maybe 3) parameters eg for data structures. (Are there others I'm missing?).
- the diffserver is written in go, as is the [sample data layer](https://github.com/rocicorp/replicache-sample-todo/tree/master/serve).
- we derived a lot of benefit from having [integration tests](https://github.com/rocicorp/replicache-client/blob/master/repm/sync_integration_test.go#L332) in replicache-client that exercise the whole stack under the bindings. The integration tests instantiate a real client, a real diffserver, and a fake data layer all in process and we test the protocol using the client's dispatch api. I think the only differences between the integration tests and real life are A) client is driven by the tests, not the bindings and B) the data layer is fake and C) the components are all running in the same process. Otherwise it's like the real thing (real http requests to real http servers, etc). 
- the [account service](https://github.com/rocicorp/account-service/) is written in go and is composed of a CLI that talks rpc to lambdas backed by an amazon RDS db. The account service is not yet complete and is not integrated with the client (eg to use account-service-generated account ids) or diffserver (eg to use account-service-managed data layer urls or to keep track of diffserver fetches by account if we do that). The account service has [integration tests](https://github.com/rocicorp/account-service/blob/6e94bfb58676f50d669313c132498376a4064354/integration_test/cli_test.go#L414) that drive the CLI talking to a real in-process account service server and a fake in process github OAUTH server. _If we decided it was worth the cost_, we could pretty easily include the account service together with the diffserver/fake data layer/replicache-client in integration tests. 

**Discussion: How to test sync**

Given that we can't instantiate a web server in wasm we have to choose how to test sync. We could 
1. Unit test sync in rust land with an in-process httpserver serving as a fake data layer or diffserver, like we do in many places in replicache-client, [for example here](https://github.com/rocicorp/replicache-client/blob/c3e422ab432afcbce1ab31a33e0021d47a192b42/db/push_test.go#L100) and in diffserver, [for example here](https://github.com/rocicorp/diff-server/blob/37135a25431fcd768c82279c9af35e9637b0fac5/serve/client_view_test.go#L63). We would always test the things that were different in wasm land in wasm land, eg fetch, and run whatever tests were easy to run from rust land in wasm. We might also have a smoke test to ensure sync is working in wasm, but we would not have the exhaustive unit testing of sync on the wasm side. 
1. Unit test sync in wasm land with mocked out http requests. Exhaustive unit testing lives in `tests/wasm.rs` or similar. 
1. Integration test sync where we start an http server implementing a fake backend service as a separate process and point wasm tests against it.

I have never had a fun time with 3, so I have a preference against it. 

Dispatch tests are currently accumulating in wasm land so it would be natural to do 2. This is good because tests are running in a context that matters. But it has the disadvantages that our sync tests get less realistic because network is mocked out and in that wasm land starts pulling all the tests into itself, and we know we are going to want to run on other platforms. 

I have a preference for 1 because it is realistic for sync. I do however think that dispatch tests should live together, and not have say sync tests in `src/embed/` and the rest of dispatch tested in `tests/`. If I could wave a magic wand I would move the source code of the dispatch tests into `src/embed/` and test sync there with in process http backends. We could package the dispatch tests that can run in wasm up separately from the sync tests that cannot so that we can _also_ run the dispatch tests that are able to be run in the browser from `tests/wasm.rs` (wasm.rs would just call the can--run-on-wasm test module that lives in embed). 

What do you think?

**Discussion: Integration testing**

A mistake I made when implementing sync in replicache-client was not implementing an integration test for the client-diffserver-datalayer interactions sooner. Had I gotten an integration test running sooner integration would have been a lot easier. However, obviously getting the same kind of in process integration test that we have in replicach-client working with repc could be challenging. I suspect we all agree that we _should_ have an integration test for repc-fakedatalayer-diffserver (and eventually repc-diffserver-fakedatalayer-accountservice). The question is when to invest. The Right thing to do is to right now-ish investigate how much work it would be by spending < 1 week trying to get the repc not-wasm client working in the go integration test (or some other approach). However I am feeling some time pressure to get a working thing and it is always tempting to just go for the finish line. But, uh, that's what we did last time :)

If I had a magic wand I would conjure an engineer and set them to trying to get the not-wasm repc client running in the replicache-client integration test instead of replicach-client itself, the goal being to see how much of a PITA it is not to actually have things working completely. If I couldn't conjure an engineer I would go do the investigation myself once I have a thing to be integrated (read: shortly).

Thoughts?

**Comment by aboodman** [comment] 2020-08-09 06:52
Thanks for the thoroughness as always ;-).

I think that we should unit test the units as we have been, in Rust, and as we did in Go.

I think we might be able to make use of the existing integration tests (!!) by embedding Rust in a Go binary or the reverse. This would be super valuable because it would give high confidence in the Rust port without tons of manual testing. I think there are a few ways to go about it:

1. We could use FFI to embed Rust in the Go program
2. We could run Rust [inside a WASM VM inside Go](https://github.com/wasmerio/go-ext-wasm)

I can't think of any difference in the level of testing between these two approaches. Any difference between them would be a WASM compiler bug or something. I'd just choose whichever seems easier.

**Comment by whiten** [comment] 2020-08-11 18:35
I like @aboodman's suggestion of reusing the existing tests from Go the most of these here, and I think the simple interface we have for the dispatch call should make this fairly straightforward. It should be simple to bring up a trivial Rust library and test writing a Go test around that with cgo, and that should eliminate most of the FFI risk involved before we got too deep too.

Regarding what's testable under different environments, I think the differences between x86 and Wasm are probably smaller than the differences between an idealized key-value store and what we're getting with IndexedDB, esp. regarding the auto-commit (which we revise to be auto-poison) behavior. I don't see a way to involve IndexedDB in the tests without writing them inside a browser, which puts us in the category of 3. from @phritz's original list. I don't have as strong a preference against that option and think it may be good over time to allow writing an integration test from the dispatch layer, through a true storage layer, and to real backend servers for both native and Rust builds down the line, but I do think it's more upfront work, and reusing the Go test lets us test what we're anxious to test most expeditiously right now.

It would be an interesting experiment for later to see if we could simulate the auto-poisoning behavior of IdbStore in MemStore for testing purposes, eliminating this difference. I don't think that's critical upfront, and I also don't think durability matters (does it?) for this initial sync testing, so I think generating a C calling convention library that exposes `dispatch` with MemStore behind it is a good option here. This would force us to wall off the Wasm-requiring pieces a bit, but I like that as a side effect that would allow more pure-Rust testing of dispatch and friends, allowing us to learn more what the Rust toolchain provides like code coverage tracking, etc.

**Comment by aboodman** [comment] 2020-08-12 19:44
> I also don't think durability matters (does it?)

Not to my recollection.

**Comment by phritz** [comment] 2020-08-12 20:47
Right, durability doesn't matter for the tests we have.

**Comment by whiten** [comment] 2020-08-17 22:38
https://github.com/rocicorp/repc/pull/106 brings over `sync_integration_test.go` from replicache-client with only minor changes. Lots of failures to work through, some of which may be valuable to fix already. One thing that stands out is that the HTTP client demands that it be run from within a Tokio runtime/reactor, and the FFI work I did so far does not provide that. Can be reproduced as below. CC @phritz 

% go test -v ./tests -run TestPull
=== RUN   TestPull
    TestPull: sync_integration_test.go:196:
        	Error Trace:	sync_integration_test.go:196
        	            				sync_integration_test.go:398
        	Error:      	Expected nil, but got: []byte{}
        	Test:       	TestPull
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', /Users/nate/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/io/driver/mod.rs:201:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    TestPull: sync_integration_test.go:408:
        	Error Trace:	sync_integration_test.go:408
        	Error:      	Received unexpected error:
        	            	The channel is empty.
        	Test:       	TestPull

**Comment by phritz** [comment] 2020-08-17 23:02
Ick. My guess is until we sort out #82 we should create a new tokio runtime in the non-wasm case and use it to block on here: https://github.com/rocicorp/repc/blob/master/src/embed/dispatch.rs#L34. Something like:
```
let mut rt = tokio::runtime::Runtime::new()?;
rt.block_on(...)
```

**Comment by aboodman** [comment] 2020-09-03 02:11
Closing in favor of more targetted bug.

**Closed by aboodman** 2020-09-03 02:11 UTC
